<a href="https://colab.research.google.com/github/19522224/CS114.L21/blob/master/LinearRegression_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Regression**

**Download data from git**

In [76]:
!curl https://raw.githubusercontent.com/19522224/CS114.L21/master/data2.txt > data2.txt
!curl https://raw.githubusercontent.com/19522224/CS114.L21/master/data3.txt > data3.txt
!curl https://raw.githubusercontent.com/19522224/CS114.L21/master/data4.txt > data4.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1175k  100 1175k    0     0  18.5M      0 --:--:-- --:--:-- --:--:-- 18.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  174k  100  174k    0     0  1323k      0 --:--:-- --:--:-- --:--:-- 1323k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   99k  100   99k    0     0   794k      0 --:--:-- --:--:-- --:--:--  794k


**Import Libraries**

In [77]:
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import pandas as pd

**Import Dataset**

In [78]:
data_df=pd.read_csv('./data2.txt')
data_df.head()

A         B
0  6083695  0.521842
1  1954367  0.152648
2  3734185  0.298548
3  5839301  0.460480
4  6343427  0.527977

**Define x and y**

In [33]:
x=data_df.drop(['B'],axis=1).values
y=data_df['B'].values

In [79]:
print(x)

[[6083695]
 [1954367]
 [3734185]
 ...
 [9837364]
 [9466593]
 [4080801]]


In [80]:
print(y)

[0.521842 0.152648 0.298548 ... 0.801394 0.776407 0.314468]


**Split the dataset in training set and test set**

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

**Show the dataset**

In [82]:
%matplotlib inline
plt.plot(x,y)
plt.show()

**Train the model on train set**

In [18]:
model= LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Predict the test set result**

In [20]:
y_predicted = model.predict(x_test)
print(y_predicted)


[0.0788111  0.43141073 0.22555698 ... 0.03496753 0.40674313 0.40845283]


**Evaluate the model**

In [26]:
from sklearn.metrics import  r2_score
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
r2_score(y_test,y_predicted)


0.9977186920864866

In [46]:
print(mean_absolute_percentage_error(y_test,y_predicted))
# source: https://www.askpython.com/python/examples/mape-mean-absolute-percentage-error

22.039193197490125


# **Test data3.txt**

READ AND ... DATA

In [36]:
data3=pd.read_csv('./data3.txt')
data3.head()

A        B
0  37837612  4.12166
1  37395246  3.92089
2  36610827  3.21540
3  29555651  2.54506
4  25928216  2.21831

In [39]:
x_data3=np.array(data3['A']).reshape(-1,1)
y_data3=np.array(data3['B'])
print(x_data3)

[[37837612]
 [37395246]
 [36610827]
 ...
 [33520323]
 [21243264]
 [21380484]]


In [40]:
print(y_data3)

[4.12166 3.92089 3.2154  ... 2.90918 1.80292 1.82795]


In [41]:
plt.plot(x_data3,y_data3)
plt.show()

**Predict the test set result**

In [43]:
y_predicted_data3=model.predict(x_data3)
print(y_predicted_data3)

[3.18392786 3.14651817 3.08018199 ... 2.81882648 1.78058899 1.79219332]


In [44]:
r2_score(y_data3,y_predicted_data3)

0.9286940615655543

In [45]:
print(mean_absolute_percentage_error(y_data3,y_predicted_data3))

4.409327016531241


# **Test data4.txt**

In [ ]:
data4=pd.read_csv('./data4.txt')
x_data4=np.array(data4['A']).reshape(-1,1)
y_data4=np.array(data4['B'])

In [ ]:
plt.plot(x_data4,y_data4)
plt.show()

In [75]:
!curl https://raw.githubusercontent.com/19522224/CS114.L21/master/data2.txt > ADREADME.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1175k  100 1175k    0     0  2365k      0 --:--:-- --:--:-- --:--:-- 2365k
